# Generated by micron-art/examples/regenerate.sh -- do not edit by hand.
# Source art lives in micron-art/examples/art/.
#
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m literal  micron-art/examples/art/gallery-mono.txt
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m escaped  micron-art/examples/art/gallery-mono.txt
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m escaped  micron-art/examples/art/gallery-color.ans
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m escaped  micron-art/examples/art/gallery-hazard.txt

>micron-art gallery

`[Back to the index`:/page/index.mu]

>>Literal mode

Wrapped in \`=, emitted verbatim. Nothing inside needs escaping, and
nothing inside can be coloured.

`=
        /\
       /  \
      /    \      /\
     /      \    /  \
    /        \  /    \
   /          \/      \
  /                    \
~~~~~~~~~~~~~~~~~~~~~~~~~~
`=

>>Escaped mode, with colour applied

The same art, escaped in place instead of wrapped. Because markup still
works, a colour tag ahead of it applies to the whole block -- Micron
carries colour state across lines.

`F0c0
        /\\
       /  \\
      /    \\      /\\
     /      \\    /  \\
    /        \\  /    \\
   /          \\/      \\
  /                    \\
~~~~~~~~~~~~~~~~~~~~~~~~~~
``

>>Converted from ANSI

Colour read from SGR escape sequences and mapped to Micron tags. Source
was a .ans file; see micron-art/docs/ansi-mapping.md for what survives
the conversion and what does not.

 `Ff00▄▄▄▄`Fff0▄▄▄▄`F0f0▄▄▄▄`F0ff▄▄▄▄`F55f▄▄▄▄`Ff0f▄▄▄▄
`f `F21c▀`F31b▀`F32b▀`F42b▀`F42a▀`F52a▀`F639▀`F639▀`F738▀`F738▀`F848▀`F847▀`F947▀`F946▀`Fa46▀`Fa56▀`Fb55▀`Fb55▀`Fc54▀`Fc64▀`Fd64▀`Fd63▀`Fe63▀`Ff72▀
`f `F0ffc`F0f0o`Fff0l`Ff00o`Ff0fu`F55fr`f from ANSI``

>>Why converting matters

Micron gives block meaning to a line's first character. A dash draws a
divider, a hash deletes the line, and an angle bracket makes a heading.
Art that starts lines with those characters is mangled by the renderer
before anyone sees it.

Here is the raw art, pasted into this page with no conversion:

--- SIGNAL ---
- rssi   -78 dBm
- snr     9.5 dB
- path   3 hops
`--------------`
# uptime 14d

Every dashed row collapsed into a full-width divider, taking its text
with it -- four readings reduced to four rules. The fenced row lost both
backticks and the dash after the first one, because a backtick opens a
formatting tag and swallows the character following it. The last line
vanished entirely: a leading hash marks a comment, and the parser drops
those before rendering.

The same art, converted:

\--- SIGNAL ---
\- rssi   -78 dBm
\- snr     9.5 dB
\- path   3 hops
\`--------------\`
\# uptime 14d

Every line is intact. The escape is a single backslash, which the parser
consumes, so the art keeps its original column alignment -- nothing is
shifted to make room.
