#!/usr/bin/env sh
# Rebuild examples/index.mu and examples/gallery.mu from examples/art/.
#
# Run this after touching the converter. The committed .mu files must
# match what this produces byte for byte; if they do not, either the
# converter changed behaviour or someone hand-edited generated output.
#
#   micron-art/examples/regenerate.sh
#
# No arguments. Safe to run from anywhere.

set -eu

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT"

ART=micron-art/examples/art
OUT=micron-art/examples
export PYTHONPATH=micron-art/src/cli

# Convert one art file. Warnings go to stderr and stay visible.
convert() {
    python3 -m micronart -m "$1" "$2"
}

# --------------------------------------------------------------- index

{
    cat <<'EOF'
# Generated by micron-art/examples/regenerate.sh -- do not edit by hand.
# Source art lives in micron-art/examples/art/.
#
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m literal micron-art/examples/art/banner.txt

>micron-art

EOF
    convert literal "$ART/banner.txt"
    cat <<'EOF'

Converts ASCII and ANSI art into Micron markup you can serve from a
NomadNet node. The art above is a converted file, not hand-written
markup.

>>Two modes, not interchangeable

Literal wraps the art in \`=, so it survives exactly as drawn. Micron
disables markup inside the block, so it is monochrome.

Escaped protects each significant character in place, which leaves
colour and formatting available. This is the mode that keeps ANSI
colour.

Neither is a fallback for the other. Pick by whether you need colour.

>>Have a look

`[Gallery`:/page/gallery.mu]

The gallery shows both modes, a conversion from ANSI colour, and what
happens to art that is served without converting it first.
EOF
} > "$OUT/index.mu"

# ------------------------------------------------------------- gallery

{
    cat <<'EOF'
# Generated by micron-art/examples/regenerate.sh -- do not edit by hand.
# Source art lives in micron-art/examples/art/.
#
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m literal  micron-art/examples/art/gallery-mono.txt
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m escaped  micron-art/examples/art/gallery-mono.txt
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m escaped  micron-art/examples/art/gallery-color.ans
#   PYTHONPATH=micron-art/src/cli python3 -m micronart \
#       -m escaped  micron-art/examples/art/gallery-hazard.txt

>micron-art gallery

`[Back to the index`:/page/index.mu]

>>Literal mode

Wrapped in \`=, emitted verbatim. Nothing inside needs escaping, and
nothing inside can be coloured.

EOF
    convert literal "$ART/gallery-mono.txt"
    cat <<'EOF'

>>Escaped mode, with colour applied

The same art, escaped in place instead of wrapped. Because markup still
works, a colour tag ahead of it applies to the whole block -- Micron
carries colour state across lines.

`F0c0
EOF
    convert escaped "$ART/gallery-mono.txt"
    cat <<'EOF'
``

>>Converted from ANSI

Colour read from SGR escape sequences and mapped to Micron tags. Source
was a .ans file; see micron-art/docs/ansi-mapping.md for what survives
the conversion and what does not.

EOF
    convert escaped "$ART/gallery-color.ans"
    cat <<'EOF'

>>Why converting matters

Micron gives block meaning to a line's first character. A dash draws a
divider, a hash deletes the line, and an angle bracket makes a heading.
Art that starts lines with those characters is mangled by the renderer
before anyone sees it.

Here is the raw art, pasted into this page with no conversion:

EOF
    cat "$ART/gallery-hazard.txt"
    cat <<'EOF'

Every dashed row collapsed into a full-width divider, taking its text
with it -- four readings reduced to four rules. The fenced row lost both
backticks and the dash after the first one, because a backtick opens a
formatting tag and swallows the character following it. The last line
vanished entirely: a leading hash marks a comment, and the parser drops
those before rendering.

The same art, converted:

EOF
    convert escaped "$ART/gallery-hazard.txt"
    cat <<'EOF'

Every line is intact. The escape is a single backslash, which the parser
consumes, so the art keeps its original column alignment -- nothing is
shifted to make room.
EOF
} > "$OUT/gallery.mu"

echo "regenerated $OUT/index.mu and $OUT/gallery.mu"
