# Generated by examples/regenerate.sh -- do not edit by hand.
# Source art lives in examples/art/.
#
#   PYTHONPATH=src/cli python3 -m micronart \
#       -m literal examples/art/banner.txt

>micron-art

`=
   ______________________
  /                      \
 |   m i c r o n - a r t  |
 |   ascii  ->  micron    |
  \______________________/
`=

Converts ASCII and ANSI art into Micron markup you can serve from a
NomadNet node. The art above is a converted file.

>>Two modes

Literal wraps the art in \`=, so it is maintained as drawn. Micron
disables markup inside the block, so it is monochrome.

Escaped protects each significant character in place, which leaves
color and formatting available. This is the mode that keeps ANSI
color.

Pick by whether you need color.

>>Have a look

`[Gallery`:/page/gallery.mu]

The gallery shows both modes, a conversion from ANSI color, and what
happens to art that is served without converting it first.
